import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import './globals.css';
import { cookies } from 'next/headers';
import { Noto_Sans } from 'next/font/google';
import NavBar from '@/components/NavBar';

export const metadata = {
	title: 'Thullo',
	description: 'Generated by create next app',
};

const notoSans = Noto_Sans({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
});

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const supabase = createServerComponentClient({ cookies });

	const {
		data: { user },
	} = await supabase.auth.getUser();

	return (
		<html className={notoSans.className}>
			<head>
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				{user && (
					<header>
						<NavBar />
					</header>
				)}
				<main className="container">{children}</main>
			</body>
		</html>
	);
}
