import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import './globals.css';
import { cookies } from 'next/headers';

export const metadata = {
	title: 'Thullo',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const supabase = createServerComponentClient({ cookies });

	const {
		data: { user },
	} = await supabase.auth.getUser();

	return (
		<html>
			<head>
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				<main className="container">
					{/* {user && <Navbar />} */}
					{children}
				</main>
			</body>
		</html>
	);
}
